Restaurant page
SamArsanios/restaurant-page pull request #1
Opened 2021-04-14 18:24 UTC by SamArsanios

In this project, I built a restaurant page that comprises different tabs(Home/Menu/Contact) using Javascript. A user is able to toggle between the  different tabs.

2021-04-14 19:42 UTC, rukundoeric commented on dist/style.css
> +
remove this comment

2021-04-14 19:42 UTC, rukundoeric commented on dist/style.css
> +    padding-bottom: 20px; */
remove this comment

2021-04-14 19:42 UTC, rukundoeric commented on src/index.js
> +
remove this comment

2021-04-14 19:43 UTC, rukundoeric commented on src/index.js
> +// main();
remove this comments

2021-04-14 19:43 UTC, rukundoeric requested changes
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The code looks clean and professional. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve
  - [ ] [MANDATORY] Kindly remove all commented codes.
  - [ ] [MANDATORY] Necessary run common commands like build, development should be in package.json inside `scripts'. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))
      ```json
        "scripts": {
          "dev": "webpack --mode development",
          "build": "webpack --mode production",
          "start": "webpack-dev-server --mode development --open" // optional
        },
      ```
  - [ ] [MANDATORY] Fix the broken image in your readme. 

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

2021-04-15 03:24 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Samson Kibrom Okbay ** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
Just one last detail to improve before you can go ahead:

- [x] Fix broken iamge in your README file:

![ ](https://i.ibb.co/Hgcv2vQ/review93.png)

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2021-04-15 06:34 UTC, rukundoeric approved these changes
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - [x] The project follows Git flow. 💯
  - [x] Code looks clean and professional 💯
  - [x] All required changes are implemented 💯

- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

2021-04-15 06:36 UTC, merged